server:
  port: 9191

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: SERVICE-CUSTOMER
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**
        - id: SERVICE-USER
          uri: http://localhost:8083
          predicates:
            - Path=/user/**
        - id: SERVICE-TRANSACTION
          uri: http://localhost:8082
          predicates:
            - Path=/transactions/**
        - id: SERVICE-ACCOUNT
          uri: http://localhost:8080
          predicates:
            - Path=/accounts/**
        - id: SERVICE-FEEDBACK
          uri: http://localhost:8084
          predicates:
            - Path=/feedback/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
