server:
  port: 8081
  servlet:
    context-path: /customer-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-customer
spring.cloud.discovery:
  enabled: true