server:
  port: 8082
  servlet:
    context-path: /transaction-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-transaction
